import {
  AppWindow,
  ArrowLeftRight,
  BadgeCheck,
  Boxes,
  BrainCircuit,
  Cloud,
  CloudCog,
  CloudUpload,
  CodeXml,
  Container,
  Cpu,
  DatabaseBackup,
  FolderSync,
  Globe,
  Globe2,
  HardDrive,
  Headset,
  Layers,
  LayoutGrid,
  Lock,
  LockKeyhole,
  Mail,
  Megaphone,
  MessageSquareText,
  MessagesSquare,
  MonitorSmartphone,
  MousePointerClick,
  PanelsTopLeft,
  Phone,
  PhoneCall,
  RefreshCw,
  Search,
  Send,
  Server,
  ServerCog,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  SquareStack,
  Target,
  Terminal,
  TrendingUp,
  Users,
  Wifi,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

/**
 * Explicit map of the icons named in `data/services.ts`. The navbar is a client
 * component, so resolving icons via `import * as Icons` there would ship the
 * whole lucide set to the browser. Add an entry here when a service uses a new icon.
 */
const icons: Record<string, LucideIcon> = {
  AppWindow,
  ArrowLeftRight,
  BadgeCheck,
  Boxes,
  BrainCircuit,
  Cloud,
  CloudCog,
  CloudUpload,
  CodeXml,
  Container,
  Cpu,
  DatabaseBackup,
  FolderSync,
  Globe,
  Globe2,
  HardDrive,
  Headset,
  Layers,
  LayoutGrid,
  Lock,
  LockKeyhole,
  Mail,
  Megaphone,
  MessageSquareText,
  MessagesSquare,
  MonitorSmartphone,
  MousePointerClick,
  PanelsTopLeft,
  Phone,
  PhoneCall,
  RefreshCw,
  Search,
  Send,
  Server,
  ServerCog,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  SquareStack,
  Target,
  Terminal,
  TrendingUp,
  Users,
  Wifi,
};

export function ServiceIcon({ name, ...props }: { name: string } & LucideProps) {
  const Icon = icons[name] ?? Sparkles;
  return <Icon {...props} />;
}
